### ISSUE TITLE
Implement list API

### ISSUE THREAD

**Issue by Omertron** [YAMJ/yamj-v3#10]
Should be able to ask for a list, page#, how many items on a page, and some sorting/filtering criteria

For example, 
- videos, page 1, 27 per page, desc sort by date added, unwatched, limit 100. (aka, the new index )
- people, page 2, 12 per page, no sort, for video 5, no limit
- episodes, page 1, 10 per page, desc sort by date added, unwatched, limit 10 (10 newest episodes)

A second part of the indexes is a little more information about the index that is needed.

Ideally, # of items in the index and a timestamp of the newest item in the index if possible. One is needed to setup the rest of the navigation, the other is to know that the index has changed while you were in it so you can adjust and reload the data if it changed.

A second call is best to me. something lightweight that you can call often if desired.

**Comment by modmax** [comment]
Already done by paging mechanism in most API requests.
