### ISSUE TITLE
add HD (resolution) filtering to API

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#145]
could you add filtering to HD (resolution) to 
api/index/video.json?type=movie,series&include=width-1920

add an API which list various résolution , perhaps need to add a table which specify the values beetween for 
SD, Half-HD, HD, 4K, .....
api/resolution

**Comment by modmax** [comment]
You can include the resolution within the index options:
Example:
api/index/video.json?type=movie,series&include=resolution-hd

Following resolutions are possible:
SD: width from -1 to 1024 (cause anamorphic DVD's)
HD/HD720: width from 1025 to 1280
FullHD/HD1080: width from 1281 to 1920
UHD/UHD1/4K: width from 1921 to 3840
UDS2/8K: width from 3841 to 7680

Everything else defaults to ALL, which means every resolution.
