### ISSUE TITLE
New API calls for sets

### ISSUE THREAD

**Issue by modmax** [YAMJ/yamj-v3#147]
Right now sets are stored in the database; but there is not possibility to query the sets via API.

1.) API call to return all sets (id, name)
2.) API call to return all movies or series within a set.
3.) Or both together as
  - set name A
   - movie 1: id and title
   - movie 2: id and title
 - set name B
  - series 1: id and title

ANd from there on the movie infos/series infos could be fetched.

**Comment by jluc2808** [comment]
what is still to implement : 
1) add poster / fanart for the set itself (workaround take the 1rst member artwork) 
2) watched is by member , if all members  are watched set watched to the set itself , ortherwise add watched incomplet status
3) API should return if the video is member of a set (+set name and set id) 
4) API allows to sort set member by rank, aired or name,

**Comment by modmax** [comment]
Following has already been done:
2.) WATCHED for a set is the combined watch of all video datas in the set
3.) With dataitems=boxset you can add the boxset informations to a video or an index

Sill open: 1 and 4.

**Comment by modmax** [comment]
4. is fixed with #216

**Comment by modmax** [comment]
4 is also implemented.

**Comment by modmax** [comment]
Artwork can be stored for a boxed set; so dataitems=artwork should solve the problem.
