### ISSUE TITLE
API video/series with dataitems=country return an error 500

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#150]
api/video/series/5.json?dataitems=genre,artwork,plot,country,files,certification,studio,rating&jobs=actor-5,director-1,writer-1

when the country dataitems is setted failed with error 500

**Comment by modmax** [comment]
Right now the country is just in videodata table ... so relations from country to movies/series/season must be present .... that should be done with issue #151 ...

So for now: Just disable the dataitems=country in your api call for series and seasons until issue #151 is solved.

I close this issue cause it's basically the same than #151
