### ISSUE TITLE
implement api/country/list 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#151]
could implement 
api/country/list.json?&type=MOVIE&sortby=country&sortdir=ASC
to return the list of counrty available 

and 

&include=country-France   in the api/index field

**Comment by modmax** [comment]
At the moment countries are just implemented for movies. There is a seperate field for country in the videodata table.

Normaly this should be enhanced to a 1:n relation from movie/series to country.

But in that case we have the same problem with genres: Each scanner may write another country for a movie/series .. ie. Germany, Allemagne or Deutschland.
So ar first there must be also some kind of country handling like now for genres.
After that this issue can be resolved ...

**Comment by modmax** [comment]
Added country handling the same way as genres are handled.

**Comment by jluc2808** [comment]
tested OK
