### ISSUE TITLE
add API to create tasks (delete) which just runs once

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#153]
to force the delete option to run just after a delete order from the skin , could you add an API call which 
will create tasks (delete) which just runs once immediatly

**Comment by modmax** [comment]
I think this is no longer needed, cause every DELETED entry will not be retrieved by API calls.
If new entrys are added with same natural IDs, then the old DELETED entries (if the should still exist) will be reactivated and set to UPDATED.
