### ISSUE TITLE
api/boxset/list.json?  return only the 1rst boxset , not the other one 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#154]
i have 2 set in the box_set database 
when i call api/boxset/list.json?
only the one is listed (id = 1, count = 1 ) 
the second one (id= 2) is forgotten 

{
    "count": 1,
    "totalCount": 1,
    "queryDuration": "0ms",
    "queryTime": "2014-12-06 23:03:06",
    "status": {
        "status": 200,
        "message": "OK"
    },
    "options": {},
    "baseArtworkUrl": "http://192.168.1.21:8888/artwork/",
    "baseMediainfoUrl": "http://192.168.1.21:8888/mediainfo/",
    "basePhotoUrl": "http://192.168.1.21:8888/photo/",
    "results": [
        {
            "id": 1,
            "name": "Harry Potter",
            "memberCount": 1,
            "watched": false
        }
    ]
}

**Comment by modmax** [comment]
Reason was: The second box set has no member.

Intention was that just boxed sets will be returned which have members (movie or tv series).

I changed this so that all boxed sets will be returned, The boxed sets without member have a member cound of 0 and no watched status.

**Comment by jluc2808** [comment]
tested ok
