### ISSUE TITLE
add awards to the scanner and API 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#168]
add awards to the filescanner, and API 
for API 
- add to dataitems 
- add API to list awards

**Comment by modmax** [comment]
I don't think that awards are scanned from the file name ... so this is just a core and api issue.

**Comment by Omertron** [comment]
Might be in the NFO file too, not sure if Kodi (XBMC) covers this, will need to check with their spec

**Comment by Omertron** [comment]
My bad, closed wrong issue

**Comment by modmax** [comment]
My suggestion is:
1.) awards are available for movies and series
2.) Each award consist of 3 fields: awardType (i.e. Academy Awards (based on scanner)), year and award dscription (based on scanner).
3.) if dataitems=awards is added then also the awards fpr the movie/series should be retrieved

What ist intended to list awards, btw. whhat is expected to be returned
a.) awart type with year?
b:) award type only?
c.) award with year and description?

If you want person awards, then a seperate issue should be created, cause that will be to much for this issue. This isseu just handles movie and series awards.

**Comment by Omertron** [comment]
Have a look at the awards in YAMJv2

Personally I don't care for them as they come from IMDB only

**Comment by modmax** [comment]
The awards yan now be scanned and retrieved by the API; right now just fpor allocine:

PreConditions:
1.) the configuration "allocine.movie.awards" is set to true (default: false)
2.) the configuration "allocine.tvshow.awards" is set to true (default: false)
3.) Set videoData/series to UPDATED to force a rescan where the awards will be fetched

API methods:
a.) /api/awards/list: This lists all available award (event and category)
b.1) videoList --> include=award-7 ... this will include all videos for awards with award id 7
b.2) videoList --> include=award-Golden Globes ... this will include all videos with awards for event "Golden Globes"
c.) singe video: dataitems=award ... retrieves also the awards

**Comment by Omertron** [comment]
I think, like yamjv2, we should have properties that are generic rather than specific to a scraper.

So the above should be "awards.tv" and "awards,movie".

You should then have "allocine.awards" true

This way you can control what plugins get what items for you (you might not like the allocine awards for example)

**Comment by modmax** [comment]
It's nearly the same, but then you cannot specify exactly what you want.

With your suggestion you could not set: Scrap movie awards from IMDB and series awards from allocine. The idea in YAMJ v2 was mainly ... configure everything as default and let the scanners do the rest ... if the have the infos or not.

But mostly you have your favorite plugin ... one have allocine, the others themovietb and thetvdb as combination. So the users should have the possibility to configure their favorite scanner ...

With the complex properties, to say yamj: scann awards fro movies and series ... YES .. but then the allocine scanner says no ... or another sanner has not those possibility ...

So mostly it's better that the common yamj settings are effecting all scanners (cause the all yan handle it); but special gadgets should be left to the plugins ...

**Comment by jluc2808** [comment]
tested ok
