### ISSUE TITLE
implement playerpath , path, device_type, device_name  to play on any device 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#175]
the player implementation is now to short to handle various kind of player with various kind of path 
i have build library.xml in bikini skin to specify what is needed to address various player on PC , PCH  (never succeed on android and apple) 

this basicly base on 
- * device_type (several)
- ** device_name (several))
- *** device_adress (only one)
- **** source_path  (the one stored inside the database when scanning) (several - as many as various path stored in stage_file database) 
- ***** substitution_path (what replace the source_path according to the player way of reading path) (1 per source_path per a specified device_name)

**Comment by Omertron** [comment]
You mean this example file? skins/bikini/My_Library.xml

**Comment by jluc2808** [comment]
yes i it's My_Library.xml (not library.xml)

**Comment by jluc2808** [comment]
revision 2eb129f is now OK for 
* device_type (several)
** device_name (several))
*** device_adress (only one)

could you add  the translation part for each device_name : 
**** source_path (the one stored inside the database when scanning) (several - as many as various path stored in stage_file database)
***** substitution_path (what replace the source_path according to the player way of reading path) (1 per source_path per a specified device_name)

**Comment by Omertron** [comment]
I am working on the "pages" part at the moment as that will drive out the API calls too.

So you will be able to go to the home, players, add a player, click that player and add multiple paths.

I will also write a reader for the library,xml file. I will probably add a page like the "add skin" page to upload a libray file.

**Comment by Omertron** [comment]
0fd06ee2d0fe92974feac70fb6cc493670abcb39 should have the correct working player info and paths

**Comment by Omertron** [comment]
Completed
