### ISSUE TITLE
add ability to add / overwrite artwork, people, synopsys

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#176]
still now there some usefull instruction (API) to delete / update movie scan 
also there is instruction (API) to ignore some artwork 
to complete theses some other API are needed , this shouldn't replace NFO, but is a more easy way to upgrade directly from the skin ; here a list of what seems to me usefull 
* artwork (poster, fanart, photo) :  adding from outside storage 
* people : add new people (needs to decide what is mandatory) and attach to a video, upgrade/modify people Biography, birthday,  
* video: replace / modify sysnopsis, add genre, replace watched / unwatched

for mediainfo i will post another issue to scan mediainfo from video inside a NAS

**Comment by modmax** [comment]
Last comment should reference to #178

**Comment by jluc2808** [comment]
you said 'last comment should reference #178'  when i speak about mediainfo i 'm talking about container, audio, video, fps, ratio , ..... 
does issue #178 address those items ?

**Comment by modmax** [comment]
No .. I just wanted to make a reference to #178, but instead made it to #176.. little typo error ... just to be clear that the reference from github checkin should belong to another issue. That's all ...

**Comment by modmax** [comment]
Added methods to add artwork from outside:

Call for API is: /api/artwork/add/{artwork_type}/{metadata_type}/{id}

where:
artwork_type: poster, fanart, videoimage,photo
metadata_type: movie, episode, series, season, boxset, person
id: id of metadata type (i.e. ID of a person)

**Comment by jluc2808** [comment]
great :  at this point several point are already implemented that allow manual update of person/movie/series
already available and tested: 
- add/ignore artwork 
- add/ignore/delete external_id
- watched/unwatched

to be done: 
- synopsys
- biography
- mediainfo (? to be checked) 


of course all these parts could be updated via NFO , but the purpose here is to let the skin updates db without the need of an NFO file and new scan.
