### ISSUE TITLE
API certification list is wrong when type is selected 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#183]
api/certifications/list.json?&type=movie&sortby=certificate&sortdir=ASC
return count equal the number of movies in the database and duplicate the results 
{
    "count": 439,
    "totalCount": 439,
    "queryDuration": "10ms",
    "queryTime": "2015-02-20 22:41:38",
    "status": {
        "status": 200,
        "message": "OK"
    },
    "options": {
        "sortby": "certificate",
        "sortdir": "ASC",
        "type": "MOVIE"
    },
    "baseArtworkUrl": "http://192.168.1.46:8888/artwork/",
    "baseMediainfoUrl": "http://192.168.1.46:8888/mediainfo/",
    "basePhotoUrl": "http://192.168.1.46:8888/photo/",
    "results": [
        {
            "id": 6,
            "country": "France",
            "certificate": "3"
        },
        {
            "id": 6,
            "country": "France",
            "certificate": "3"
        },
  
api/certifications/list.json?&type=series&sortby=certificate&sortdir=ASC is wrong 0 results

**Comment by modmax** [comment]
The issue with duplicate certifications has been fixed.

But I have no issue with series certifications. If there are entries in "series_certifications" than those certifications will be shown ...
NOTE: The allocine TV series have no certifications. Just movies have certifications which are returned by the allocine API.
