### ISSUE TITLE
API: add year list 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#184]
could you add a year list in the API (like in yamjv2)
with selector which allow to specify the list interval 
like 
- decade (list by available decade) 
- year (list years available) 

 add the video list for such interval 
- allow to specify : older than (return  list of older than : a year) 
- and newer than (return  list of newer than : a year)

**Comment by modmax** [comment]
I would like to add following API calls:
* /api/video/decades/list?type={movie,series,season,episode)
Returning a list only containineg decades like: 1980,1990,2000,2010 etc.
* /api/video/years/list?type={movie,series,season,episode)
Returning a list only containing the years: 1981,1982,1983 etc. pp.

Then the client knows, which decades are present and can be used.
Then a second call is for the movie index with:
* startyear=1910
* endyear=1919
or
* decade=1910, where it's the same than setartyear=1910&endyear=1919

**Comment by modmax** [comment]
Following API calls are implemented:
/api/video/decades/list[?type={movie,series,season}]
/api/video/years/list[?type={movie,series,season}]

**Comment by modmax** [comment]
Within the index you can specify following parameters:

**Comment by modmax** [comment]
Within the index paramaters you can specify yearStart and/or yearEnd.
* /api/index/video?type=movie,series&searStart=1990&yearEnd=2000

With this mechanism you can also fetch decades, or any other kind of year ranges.
