### ISSUE TITLE
add API to fetch / update videodata_ids abd update status of videodata

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#187]
to allow (from the skin) to update a movie 
1 - add an API request which fetch / change status of videodata to UPDATED (now there is a an API to update stage_file only) 
2 - add an API request which fetch / change the sourcedb_id and source_db 
 - 4 actions fetch,  delete , change , add

**Comment by Omertron** [comment]
This should be fixed now.

**Comment by jluc2808** [comment]
propagation isn't complet

tested with stage_file 339 - videoata = 221 
i change the videodata_ids for 221 with allocine 166884 (old value 166885) directly in the db
and ask for update using : api/file/update/399

results : 
[00:40:13] INFO  org.yamj.core.api.json.FileController  - Updating file '399'
[00:40:38] INFO  org.yamj.core.service.mediaimport.MediaImportService  - Process updated video 399 - '12 Years A Slave (2013) - 1080p.Bluray.mkv'
[00:40:38] INFO  org.yamj.core.service.ImportScheduler  - Processed video stage file: 399
[00:40:43] INFO  org.yamj.core.service.ScanningScheduler  - Found 1 media files to process; scan with 1 threads
[00:40:43] DEBUG org.yamj.core.tools.LanguageTools  - Scanning media file T:\video\Film\12 Years A Slave (2013) - 1080p.Bluray.mkv
[00:40:48] DEBUG org.yamj.core.service.ScanningScheduler  - Finished media file scanning


but the videodata havn't been updated anymore 
last update timestamp : '2015-04-09 21:50:27'  

if updated 
last update timestamp  should be: '2015-05-13 00:40:48'

**Comment by Omertron** [comment]
The API needs to be used to add the ExternalIDs, this will also set the status of the VideoData to Update which should then force an update (I Think)

**Comment by jluc2808** [comment]
all the mecanism you describe is right , but at least the movie is partially updated 

i will try to describe what i want to do and want is the exact result i found 

i have amazing spider-man which have been scrapped and stored earlier but the with amazing spider-man 2 contents 
i want to renew the contents with the right goal with allocine id = 128188
i 'm using api/video/externalids/update.json?id=404&sourcedb=allocine&externalid=128188
and the job is proceeded  - log abstract
[23:04:05] INFO  org.yamj.core.database.dao.ApiDao  - Updating 'allocine' ID from '192186' to '128188' for 404-The Amazing Spider-Man : le destin d'un Héros
- title, plot, date, .... are performed ok but 
-  fanart aren't updated because 5 fanart are already stored from the previous one 
- poster are added but in addition with the old one (the poster of the previous one) 

so the result is partial  : 
plot , title, date are OK 
fanart are the old one (KO) 
poster merges old one and new one (KO) 

so my purpose is to enforce a complet rescan of a movie,  including a renew of artwork.  the situation of a wrong movie scrapped which need to be renew with the right id is something i often found .

**Comment by jluc2808** [comment]
suggestion : 
add an  API  : 
1.) api\file\new\{id}
- where ID is the ID of the stage file in the database
-  reset status to NEW on all the dependencies (videodata, artwork, participation, .....)  and  perform a clean update of each contents with a new rescan from the net.

**Comment by modmax** [comment]
Fixed with #219
