### ISSUE TITLE
add an API to rescan person and filmography 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#188]
allow skin to rescan a person and  filmography 
1- API which update person_id status and filmography_status 
avalaible value for status :  
- delete, new , updated
available value for filmography_status: 
- new , updated

**Comment by modmax** [comment]
Added API calls to rescan metadata, which sets the status of the metadata to UPDATED.

/api/rescan/movie/{id}
/api/rescan/series/{id}
/api/rescan/season/{id}
/api/rescan/episode/{id}
/api/rescan/person/{id}
/api/rescan/filmography/{id}
