### ISSUE TITLE
API to set or reset Watched flag 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#193]
could we add an API entry to set or reset the watched flag for 
- movie, episode, season, series

**Comment by Omertron** [comment]
#46

**Comment by jluc2808** [comment]
api/unwatche/movie/131 unset watched_api value as required , but the general api which fetch for video like 
api/index/video.json?type=MOVIE&sortby=title&sortdir=ASC&artwork=poster&watched=all
return watched= true because watched_file = 1 which isn't reset by api/unwatched  and shouldn't according with to the fact that the movie have a watched file and still stored. 

 1 - so there is conflict between the 2 values (3 if i add watched_nfo) which in the db too 

1rst solution to solve the problem is to set a value of -1 for the unwatched api or nfo value rather than reset to 0 , let value=0 by default if nothing have been done 
and use a combined value which the following rules : 
- if all value are 0 (watched_api, watched_file, watched_nfo) then api results should return watched=false
- if one or more value = 1 (of watched_api, watched_file, watched_nfo) and the other value are 0 then api results should return watched =true 
- if  watched_api , or watched_nfo = -1 then api results should return watched=false

 but  this doesn't solve all the potential conflicts ,  filescanner is rerun and find the watched file (the same or new one created by another mechanism or manually) , the nfo have a new watched value 

2nd solution need to compare watched value by updated date and take the last updated watched_XX value  - could be done with file (stage_file of the watched file) , nfo (stage_file of the nfo) , but there is no updated date for watched_api 
- the rule is : take the value of the last updated watched_flag (whatever could be the value of the otherone )  0 and 1 are enought in that case

3rd solution is to set a priority parameter, like:  nfo, api, file + set a value -1 when unwatched is setted with api , nfo or watched file deleted 
the rules is : take the value of the prefered parameter if -1 or 1 , go to the next one if 0
to set -1 value api/unwatched should be used,  nfo watched value should be setted to false and watched file have to be deleted

**Comment by Omertron** [comment]
The idea with watched is that you can use various methods to mark a file as watched. Either with a NFO file (used by XBMC for example), a `*.watched` file (used by YAMJv2) or by triggering the API from the skin.

The question here is whether the API should overwrite the other methods and take priority, or if it should work in conjunction with those methods.

Perhaps, as suggested a timestamp could be used to sort the watched information and then if the user used the API to UNSET the watched status, this would take precedence over the other methods.

**Comment by jluc2808** [comment]
i agree with the watched timestamp solution (my 2nd solution) 
API should return the watched status of the lastest timestamp value (NFO, File, API)

**Comment by modmax** [comment]
The solution is now:
When setting watched flag for file/nfo/api then the timestamp of the change will be stored.

The watched flag of the video is then the watched flag of the newest api/file/nfo watche entry.

Notes:
* The relevant watched flag is stored in "watched" and this is the one which will be returned from the api.
* All other watched values are needed for the evaluation of "which is the latest watched" status.
* For files the "unwatched" is determined if the media file is not watched anymore. If a previous file is unwatched (cause watched file is missing) then the actual date will be used for the "watched_file_date".
* Same for NFO then for Files, cause if you delete an NFO file, that contained the watched flag, then also nobody can determin when the watched state has explicitly been changed.
