### ISSUE TITLE
allow to fetch filmography from a site which could be another one from the main person 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#195]
allow to set a site and alternate for person scarpping 
yamj3.sourcedb.scanner.person=imdb
yamj3.sourcedb.scanner.person.alternate=tmdb

and set another site for filmography
yamj3.sourcedb.scanner.person.filmography=allocine
allocine.person.filmography=true

**Comment by modmax** [comment]
In the static properties you now can set:
yamj3.sourcedb.scanner.person.filmography=allocine
yamj3.sourcedb.scanner.person.filmography.alternate=tmdb

Note that the alternate scanner is only called, when the main scanner fails; also it's not possible to force alternate scan, if main scanner was successful.
Reason is, that the filmography in the database is just for one scanner; cause there is no possibility to comprare filmography from different sources.

Following properties in the configuration table are obsolete now and will be deleted:
allocine.person.filmography
themoviedb.person.filmography

**Comment by jluc2808** [comment]
tested ok
