### ISSUE TITLE
add in api/video/movie dataitems=info_sources (ids of scanned sites) 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#200]
returns info about source sites scanned like allocine /imdb /tmdb 
the contents of videodata_ids table 

allow to update theses info with API

**Comment by Omertron** [comment]
Is this different from #187

**Comment by jluc2808** [comment]
it's not different but complementary 
in #187 you have added a new API entry api/video/externalids?id=8
my 1rst request is to add externalids as an dataitems , like api/video/movie/8.json?dataitems=externalids

my 2nd request is to allow to update externalids with API
- api/file/delete/stage_file_Id.json?sourcedb=imdb&externalid=tt123456
- api/file/add/stage_file_Id.json?sourcedb=imdb&externalid=tt123456

**Comment by Omertron** [comment]
Delete and update ExternalIds have been added.

**Comment by jluc2808** [comment]
tested add / delete / dataitem   - everything OK
