### ISSUE TITLE
update stage_file doesn't propagate completly to videodata

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#201]
when changing the status of stage_file to UPDATED or NEW 
core and jetty start to perform the new status but videodata isn't really updated completly 
- no new poster, fanart, person scrapped 
- it seems that only the 1rst videodata_ids is performed and partially 

the test is to change the status of the videodata itself rather than the stage_file then new poster, fanart, are scrapped at this time 

test could done with 
Les Extraordinaires Aventures d'Adèle Blanc-Sec.mkv 

settings: 
yamj3.sourcedb.scanner.movie=allocine
yamj3.sourcedb.scanner.movie.alternate=tmdb
yamj3.sourcedb.scanner.person=allocine
yamj3.sourcedb.scanner.person.alternate=tmdb
allocine.person.filmography=true
themoviedb.person.filmography=true

1- 1rst scan (with filescanner) update with only allocine external_id 

change settings 
yamj3.sourcedb.scanner.movie=tmdb
yamj3.sourcedb.scanner.movie.alternate=allocine
yamj3.sourcedb.scanner.person=tmdb
yamj3.sourcedb.scanner.person.alternate=allocine
allocine.person.filmography=true
themoviedb.person.filmography=true

2 - restart jetty et update stage_file to UPDATED 
nothing new is scrapped and status of videodata become NOTFOUND 

3 - add manually a new videodata_ids 
561 (id of videodata) 35552 tmbd 

4 - change the stage_file status to UPDATED 
no new poster/ fanart and the status of videodata stay NOTFOUND

5 - change the videodata to UPDATED 
new poster and fanart are performed from tmdb site 
videodata status is now : DONE

**Comment by modmax** [comment]
Right now it will just be checked, if the stage file has to be updated ... perhaps due different timestamps and so on .. along with this the media file will be updated ...

The rest is already part of #187
