### ISSUE TITLE
add API to get / update player info

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#202]
as player info (device, path, id, ip) is now implemented #175 
skin needs API to get/set/update these info from the db itself

**Comment by modmax** [comment]
New API calls:
* /api/player/list 
* /api/player/list?playerName&lt;playerName&gt;&mode=&lt;START|END|EXACT|ANY&gt;
* /api/player/store?name=&lt;playerName&gt;&deviceType=&lt;device&gt;&ipAddress=&lt;ipAddress&gt;
* /apli/player/delete?playerId=&lt;id of player&gt;

* /api/player/path/store?playerId=&lt;id of player&gt;&sourcePath=&lt;source path&gt;&targetPath=&lt;target path&gt;
* /api/player/path/delete?playerId=&lt;id of player&gt;&pathId=&lt;id of path&gt;
