### ISSUE TITLE
missing some results with api/alphabetical/list.json?type=movie 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#204]
i suspect some missing results with 
api/alphabetical/list.json?type=movie 

by exemple : K isn't returned and i have Kung Fu Panda stored (title, original_title, title_sort are with that name)

**Comment by jluc2808** [comment]
f1f133a  doesn't fix missing results , K is not listed (and should be) 
api/alphabetical/list.json?type=movie

**Comment by Omertron** [comment]
`title_sort` is the field that is used for the alphabetical list.

If you have pmpMyAdmin you can run this query to get the results:
```sql
SELECT DISTINCT UPPER(left(vd.title_sort,1)) AS name 
FROM videodata vd
WHERE vd.episode >= 0
ORDER BY name
```

**Comment by jluc2808** [comment]
Stuart ran the query with the same results that the api , K is missing as well 

 

If I change with 

SELECT DISTINCT UPPER(left(vd.title_sort,1)) AS name FROM videodata vd WHERE vd.episode >= -1 ORDER BY name

 

The list is now complete

 

De : Stuart Boston [mailto:notifications@github.com] 
Envoyé : samedi 16 mai 2015 11:10
À : YAMJ/yamj-v3
Cc : jluc2808
Objet : Re: [yamj-v3] missing some results with api/alphabetical/list.json?type=movie (#204)

 

title_sort is the field that is used for the alphabetical list.

If you have pmpMyAdmin you can run this query to get the results:

SELECT DISTINCT UPPER(left(vd.title_sort,1)) AS name 
FROM videodata vd
WHERE vd.episode >= 0
ORDER BY name

**Comment by jluc2808** [comment]
the where order is wrong 
change 
WHERE vd.episode >= 0 
to 
WHERE vd.episode >= -1

could you change the query in the API

**Comment by modmax** [comment]
For movies it's more correct to select with "WHERE vd.episode < 0",
cause movies have no episodes ... and episodes always have an episode >= 0.

Rerason is, that episodes and movies are stored in the same table, cause both are video data objects.

**Comment by jluc2808** [comment]
tested , work fine now
