### ISSUE TITLE
allocine filmgraphy scanned even with allocine.person.filmography=false

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#215]
if i  set 
yamj3.sourcedb.scanner.person=allocine
yamj3.sourcedb.scanner.person.alternate=tmdb
allocine.person.filmography=false
themoviedb.person.filmography=true

restart jetty , set filmgraphy_status to UPDATED
filmography is still  scanned from allocine 

logs : 
[07:40:53] INFO  org.yamj.core.service.ScanningScheduler  - Found 1 filmography objects to process; scan with 1 threads
[07:40:53] INFO  org.yamj.core.service.metadata.online.OnlineScannerService  - Scanning for filmography of person 795-'Julia Jones' using allocine
[07:40:53] DEBUG org.yamj.core.service.metadata.online.OnlineScannerService  - Person filmography 795-'Julia Jones', scanned OK
[07:40:53] DEBUG org.yamj.core.service.metadata.MetadataScannerService  - Updated person filmography in database: 795-'Julia Jones'
[07:40:58] DEBUG org.yamj.core.service.ScanningScheduler  - Finished filmography data scanning

**Comment by modmax** [comment]
There was in issue with 2 person scanner, whch are both enabled for scanning the filmography.
Now I changed the behaviour for cases, in which the alternate person scanner is enabled for scanning the person filmography, but not the "normal" person scanner.

Further on:
Note that you have 2 kind of property-files: the static and the dynamic properties.
The static properties will always be regarded, but the dynamic properties are just for the first run of YAMJ v3, where toe properties are stored in the config table.

So if you want to achive that:
allocine.person.filmography=false
themoviedb.person.filmography=true
You must change the database configuration and not the config file.

Also note, that a filmography is just for allocine or tmdb, but a filmography cannot be scanned for both ... so you never have a mix of film particpations from different sources, cause you cannot merge the film participations of something which is not comparable.

**Comment by jluc2808** [comment]
the problem is partially solved because no filmography is scrapped from allocine (never) 

so if i set  (in the static file) 
yamj3.sourcedb.scanner.person=allocine
yamj3.sourcedb.scanner.person.alternate=tmdb
allocine.person.filmography=true 
themoviedb.person.filmography=true

filmography is empty

**Comment by modmax** [comment]
The values
allocine.person.filmography=true
themoviedb.person.filmography=true
in the static file have no impact.

See the same values in the configuration table to enable/disable filmography scan.

**Comment by jluc2808** [comment]
of course when i set these parameters i restart jetty to take them in the config

**Comment by modmax** [comment]
1.) The static properties aren't taken into config, only dynamic properties. Reason is that the static properties is something, which should be just set at startup of jetty and after that changes in that file will not pe processed.
2.) The dynamic properties are stored in the database in the table configuration; they can be changed during runtime. On startup of jetty the dynamic properties aren't updated in the configuration table, cause those values could have been changed by the API.

So the solution is to change those values 
allocine.person.filmography=true
themoviedb.person.filmography=true
directly in the darabase, and not via properties.

Or have you change the values in the configuration table? YOu can achive this by using the adminstration pages; where you can configure the YAMJ3 core instance.
