### ISSUE TITLE
adding dataitems (source, rating, ...)  to api/index/video 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#216]
i want to apply source overlay to the main index page (as in yamj2) 
i'm using api/index/video.json?type=movie,series&sortby=title&sortdir=ASC&artwork=poster&watched=all which didn't return some additional info like:   source 

could you add dataitems selector to add several field like source, rating, boxset (part of a boxset)  in the api return info which is needed at this level for the skin to apply overlay

**Comment by modmax** [comment]
Added a new dataitem "boxedset" in order to return the boxed sets, the movie/series/season/episode is contained. Applyable to single video and index.

**Comment by modmax** [comment]
The rest of the items has already been done with #203
