### ISSUE TITLE
can't enforce skipping allocine 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#217]
i have scanned a new movie : last knights (2015).mkv 
as this movie is referenced as not already aired the scanner return no fanart, ouline, ....
so i want to skip allocine (only for that movie) 
- 1rst i delete in videodata_ids the allocine entry which the one the movie (548)
- 2nd i add manualy the tmdb reference in videodata_ids 
- 3rd i reset the status of videoadata to UPDATED 

consequence :  the movie is firstly scanned with allocine and doesn't take the tmdb reference 

2nd try :  i add an NFO file which give only tmdb as target 
< movie >
      < id moviedb="tmdb" >308504< /id >   
      < title >Last Knights< /title >
      < titleSort >Last Knights< /titleSort >
      < originalTitle>Last Knights</originalTitle >
< /movie >

i restart the filescanner , which find the new NFO , but scan firstly allocine and doens't scan tmdb 

so i get back to the beginning , the movie is not completed at all 

is there a way to enforce skipping allocine , which doesn't need to stop jetty , change parameter priority, restart jetty ?

**Comment by modmax** [comment]
There are several solutions for this:

1.) in videodata set  the field "skip_online_scans" to "allocine" or "allocine;imdb" or any other combinatuion of online scanner. In that case the scanner will be gnored during scan.
2.) If you set the field to "all", then all online scanners are disabled
3.) In the NFO set <id moviedb="allocine">-1</id>; the same way than in YAMJ v2.
4.) When you just set <id>-1</id>, then all online scans will be disabled.

After that you can set the status to UPDATED and the video will be rescraped.

**Comment by jluc2808** [comment]
right for the explanation of 1) in videodata set the field "skip_online_scans" to "allocine" or "allocine;imdb" or any other combinatuion of online scanner. In that case the scanner will be gnored during scan.

so the solution have to be added to the API 
/yamj3/api/video/skip_online_scan?id={}&sourcedb={}

**Comment by modmax** [comment]
I've added issue #218 for this request
