### ISSUE TITLE
Add api method to enable/disable API scanning for a movie or series

### ISSUE THREAD

**Issue by modmax** [YAMJ/yamj-v3#218]
There should be two methods to enable or disable pnline skin for a movie or series.

enableOnlineScan?id=<dbi>?source=<moviedb>
disableOnlineScan?id=<dbi>?source=<moviedb>

**Comment by modmax** [comment]
Following methods are available:

/api/video/movie/enableonlinescan?id=1&sourcedb=allocin
/api/video/movie/disableonlinescan?id=1&sourcedb=allocine
/api/video/series/enableonlinescan?id=1&sourcedb=allocin
/api/video/series/disableonlinescan?id=1&sourcedb=allocine

**Comment by jluc2808** [comment]
tested ok but could you add the status online_scan_skipped: true / false  to the api return for each sourcedb
api/video/movie/561.json?dataitems=externalid
