### ISSUE TITLE
Rework handling of external id's

### ISSUE THREAD

**Issue by modmax** [YAMJ/yamj-v3#219]
Right now externalIds are only handled for movies; but the same mechanism should also be applicabale for series, season and episodes.

Note: If the id of a series or season is changed, then the matching IDs for the sourcedb in seasons and episodes mist be reset and the status of those objects must be set to UPDATED to force a rescan.

For movies the status must be set to UPDATED if the sourcedb has been changed.

**Comment by jluc2808** [comment]
"For movies the status must be set to UPDATED if the sourcedb has been changed." or enable / disable ,  i agree so this need to be setted in an API entry to allow skin to specify update/new of the videodata status , only file stage_file could be updated till now and this is not enought

**Comment by modmax** [comment]
That request can be seen as part of #188, or at least #198

**Comment by modmax** [comment]
Still open, cause some more has to be done, if the ID changes:
* Delete located artworks from all online scanners
* reset title to title from identifer
* reset year to year from identifier
* reset all fields whicl are fille during scan
* remove cast
* remove filmography 
* mark all located artworks as deleted
* reset all ratings etc. pp.

Finally we must have a naked construct in the same manor as the movie has just been imported, without id. Or is there an error in this way?

**Comment by jluc2808** [comment]
if the end-user specify an id , then video need to be totally reconstruct based on this id ,
if he specify a sourcedb to skip every field  and info from this sourcedb need to be overwrited 
this have to be applied to cast , artwork, rating, studio, awards

so the the proposition above is the right one .

**Comment by modmax** [comment]
That may be just half of the truth:
What is, of you have main scanner skipped and use an alternate scanner?

Best effort:
1.) if external id of main scanner is changed, then reset all fields, drop cast etc. .. just like mentioned above. Set to updated.
2.) If external if of alternate scanner is changed, then just remove override flags for that source, to allow resca after setting to UPDATED. Drop just cast and delete artwork for that scanner
3.) If external id is neither for main or alternate scanner, that just remove id.

**Comment by modmax** [comment]
Solution: For evered "modified source" the relevant values wil be dropped.

**Comment by modmax** [comment]
The API calls are ready and most of the data will be dropped, if the external id of a source is changed or removed.

Following API calls are present
* /api/video/{movie,series,season,episode/updateexternalid?id=&sourcedb=&externalid=
* /api/video/{movie,series,season,episode/removexternalid?id=&sourcedb=
* /api/person/updateexternalid?id=&sourcedb=&externalid=
* /api/preson/removexternalid?id=&sourcedb=
