### ISSUE TITLE
Ability to "name" the database

### ISSUE THREAD

**Issue by Omertron** [YAMJ/yamj-v3#22]
Could be a setting in the properties file that can then be returned by the API

**Comment by modmax** [comment]
Why should a database be named?

If you use a MySQL database then you have named the database, cause you must create such a database. And then you just have to update the static properties with that information.

For a HSQL database the schema is always named yamj3, cause it's in inproc database, which just runs when the core is running.

**Comment by Omertron** [comment]
I think this was an idea to separate out the databases if you wanted a TV db and a Movies db, or Kids db and Adult db.

You're right, I'm not sure this is needed
