### ISSUE TITLE
add API to enable/diable externalID for person 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#224]
as for movie/series 
could you add the API to enable / disable external_Id 

api/person/disableonlinescan.json?id={personId}&sourcedb=[sourcedb}
api/person/enableonlinescan.json?id={personId}&sourcedb=[sourcedb}

**Comment by modmax** [comment]
Implemented:
api/person/disableonlinescan.json?id={id}&sourcedb=[sourcedb}
api/person/enableonlinescan.json?id={id}&sourcedb=[sourcedb}
