### ISSUE TITLE
remove external_id for a movie or person rebuild the external_id removed 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#227]
when i remove an external_id for sourcedb , the person or movie is rescanned ==> this OK 
but during the rescan the same external_id for the sourcedb remove is rebuild and the result is the external_id list is still the same before and after the remove order.

**Comment by modmax** [comment]
What is expected? 
If the movie or personis rescanned, than it might by that the same sourcedb id woul be returned.

I think that remove external ids is mentioned for false detected ID's ...

**Comment by jluc2808** [comment]
i think that the removed external_id should be excluded from the next scan

**Comment by modmax** [comment]
For excluding external ID's the "skip-scan"-function should be used.
The removal of external ID's is just for false or unwanted ID's; not for skipping scans, when the external ID is removed.

If the external ID in the runs is okay, then you should remove the external ID and set skip the scan with the false-detecting person/movie/series scanner.
