### ISSUE TITLE
System API to return latest timestamps of tables

### ISSUE THREAD

**Issue by Omertron** [YAMJ/yamj-v3#23]
The calls to things like genres, certifications, studios, things we might offer as indexes or filters or search things really needs a way to find out if they have changed.. maybe the best place is to add it to a new system call. You can't go by count because there could be a 1 removed and 1 added situation so some type of datastamp or something of when the last one was added.

something like /system/database_status

returns:
genres: newest timestamp
studios: newest timestamp
video: newest timestamp
... etc.

**Comment by modmax** [comment]
I don't see the necessary for gettings such informations ... this seems only important if the client want's to cache the genres, studios and so on ... but therefore the API calls are mentioned .. and the core desires what should be retrieved and what not.

Due the fact that it seems not necessary right now I close this issue.
