### ISSUE TITLE
Refactoring of localization

### ISSUE THREAD

**Issue by modmax** [YAMJ/yamj-v3#234]
Following aspects should be regarded:
* The default locale from the system should be used for every language/country checking
* The default settings should be overwritten by static properties
* Scanners should fallback to default language or country if special language not set

**Comment by modmax** [comment]
Following has been done:
* Use country code within table country only; there is no need to set a xml or api target for a country, cause the country code is unique
* country code also stored within certifications
* add "language=en" to the api calls, and the countries will be returned as localized values

It may be that some countries or certifications may be missing, cause the scanner just use the localized strings. This can be enhanced by adding the missing countries into property files directly in the YAMJ core. 
The localization should just be done by YAMJ; for YAMJ only the country codes are relevant; the localization has been done for API purposed and better lanmguage handling.

**Comment by jluc2808** [comment]
i don't understand if the country code could be setted by API or not ? (within skin)
could the country description take : french, France , FRANCE, fr , like in yamj , perhaps set the equivalent string in a available_language field

**Comment by modmax** [comment]
I think you are at work and holiday ... :-)

Oka .. now a litte excurse:
Previous versions of YAMJ just take the country or language as it is; like France, Frankreich ... and also languages like french, dutsch, deutsch, german, allemangne ..-.. and so on.

Now I refactored the whole localization part:
a.) The countries are not stored with names,insteag the iso-3166 part takes place: the 2 digit country codes; which are unique enugh for computers and also for YAMJ.
b.) The languages are not stored with their names; instead the iso-639-1 part takes place; the 2-digit languages like "en" or "fr" or anything else, what has a 2 letter digit country code.


1.) Main language for YAMJ is the default language of the computer YAMJ is running in; in my case de_DE; in your case it should be fr_FR .. but YAMJ writes a log entry where the country and languages is printed. You can overwrite it within the static properties with "yamj3.language=en" and "yamj.country=US"; or whatever you want.

2.) For TMDB set dynamical properties (in config table) for themoviedb.country and themoviedb.language .. same for imdb and thetvdb.
With this you signal, that you want to use en_US for TMDB .. or something else than the default language for YAMJ (which has been determined in part 1).

3.) The scanner all use the same mechanism to scrape countries: They determine the ISO country cod, which will be stored.

4.) API calls can include "&language=fr"; to denote that the country codes and language should be delivered for that language; if language is missing in API call then the default YAMJ language (from part 1) is used.

This has several advantages: 
a.) You only have country codes and language codes; no mix between different languages and scanners.
b.) The "localization", that means the computing from country code into country name for the desired languages is done on-the-fly .. by using the java built-in locales for languages and countries.
The localized country/language is the ISO representation of a country/language for a code.
c.) API can decide if it wants to use the codes or localized country/language.

Main disadvantage:
Some scanners have non-iso-country names; i.e. "United States of America", "USA", "U.S.A";
this will lead to warning that no country/language code could be determined; such values will be ignored.
BUT: Therefore I added properties in YAMJ to add alternate country names for a language code during scanning; so that a country code can be determined.

So @ the end:
Can you send me an excel or list of your database tables
"certification", "countries", "audio_coded" BEFOREyou install the newest version?
The newest version will fix your database (re-create-indices, drop column, create new columns, update content from country/language to codes .. and so on).

WIth you informations I then could update the property files so that a migration will be successful.
