### ISSUE TITLE
file scanner priority instead of main and alternate

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#237]
question : as for person and filmography why filescanner still stays with main and alternate , rather than take priorities list as the right order to process

**Comment by modmax** [comment]
There are no main and alternate scanners anymore.

You can just set in the static properties:
* yamj3.sourcedb.scanner.movie=tmdb,imdb
* yamj3.sourcedb.scanner.series=tvdb,tmdb
* yamj3.sourcedb.scanner.person=tmdb,imdb
* yamj3.sourcedb.scanner.filmography=tmdb

The first scanner is still regarded as the "main" scanner, while all other scanners are "alternates".
Be aware, that normally just the main scanner will be used; to scan with all alternate scanners, you just can set following values to true in the dynamic properties.

* yamj3.sourcedb.scanner.movie.alternate.always=false
* yamj3.sourcedb.scanner.series.alternate.always=false
* yamj3.sourcedb.scanner.person.alternate.always=false
* yamj3.sourcedb.scanner.filmography.alternate.always=false

Reason is that scanning might take a while and therefore no alternate scans should be done.

If you have any comments, then post them here.

**Comment by jluc2808** [comment]
i understand what you mean, but my purpose is about the way you discribe (with 2 scanner as a limit ? ) and the way which seems to me more complete that allow more than 2 scanner (perhaps i'm wrong because there is no scanner number as a limit)

you specified
 •  yamj3.sourcedb.scanner.movie=tmdb,imdb

i thought more complete 
•  yamj3.sourcedb.scanner.movie.priority=allocine,tmdb,imdb,ofdb, ....
as you said The first scanner is still regarded as the "main" scanner, all other scanners are "alternates".

and for 
•  yamj3.sourcedb.scanner.movie.alternate.always=false
it's mean that only unknown field are scrapped with alternate 

•yamj3.sourcedb.scanner.movie.alternate.always=true
it's mean that all field are rescanned with alternate

**Comment by modmax** [comment]
The static properties are just for the initial setzp ... you xan set as much scanners as you want ... do its just limited to all scanners

**Comment by modmax** [comment]
the main scanner is always done ... if it's ok then rhe scan results in ok and no further scan with another scanner will be done ... if its not okay ... then the next scanner from list is used and so on 

the alternate flag is for scanning with all gven scanners, even if previous scan with scanner in llist was okay ... the previous scanned values will not be overwritten, just missing values will be added

**Comment by jluc2808** [comment]
great, this global strategy is the right one for both parameters  , i will test various combination as soon as i could do it. 
now if we are looking with the skin point of vue i would like you confirm the following: 
- the skin could skip a source with externalID skip order ==> the API enforces a new scan and skip this source from the scan 
- the skin could enforce a new externalID with add order ==> the API enforces a new scan and will add the source added with this new scan 
- the skin could delete a source ==> the API run a new scan with all the scanner strategy implemented 

the only thing i would like is to start once a new scan of the entire Library from the skin , now it's only possible with a command out of the API and with a command (.cmd or .sh)

**Comment by modmax** [comment]
ACK to all three points.

Last point also solved:

Use /api/rescan/all to force a rescan of all movies/series/season/episodes/person/artworks
