### ISSUE TITLE
issue on filename scanner

### ISSUE THREAD

**Issue by deblockt** [YAMJ/yamj-v3#238]
I have an issue with the filenameScanner.
I have a file "Les.Aventures.de.Tintin.S0E01E02.Le.Crabe.aux.Pinces.d'Or.DUAL.FR-PT.DVDRip.XviD-XTC.[emule-island.com]"

The title is "Les.Aventures.de.Tintin", but .de. is accosiate with the Deutch language.
So my final title is "Les.Aventures"

**Comment by jluc2808** [comment]
perhaps change the .de. with blank  de blanck

**Comment by deblockt** [comment]
This doesn't work. But I have change the configuration and this work.

**Comment by modmax** [comment]
Another solution:
Set filename.scanner.language.detection=false in your user.static.properties
