### ISSUE TITLE
filescanner don't send all files

### ISSUE THREAD

**Issue by deblockt** [YAMJ/yamj-v3#239]
I don't undestand something,

I lanch filescanner one directory. I have 100 videos.
I wait the end of yamj-core.
When I look on the web application, i don't have all my films.

I recall filescanner, and after end of yamj-core work, I have more video on my web application.

I need to do that while all file are not scanned.

Know you why I have this glitch?

**Comment by modmax** [comment]
Merged pull-request .. should be fixed now.
