### ISSUE TITLE
duplicated player return with api/player/list.json?

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#254]
with api/player/list.json?

player return are duplicated as many time as there is path setted 
"count": 10,
    "totalCount": 10,
    "queryDuration": "10ms",
    "queryTime": "2015-09-02 21:09:34 +0200",
    "status": {
        "status": 200,
        "message": "OK"
    },
    "options": {
        "mode": "EXACT"
    },
    "baseArtworkUrl": "http://192.168.1.10:8888/artwork/",
    "baseMediainfoUrl": "http://192.168.1.10:8888/mediainfo/",
    "basePhotoUrl": "http://192.168.1.10:8888/photo/",
    "baseTrailerUrl": "http://192.168.1.10:8888/trailer/",
    "results": [
        {
            "id": 1,
            "name": "C200",
            "deviceType": "PCH",
            "ipAddress": "192.168.1.30",
            "paths": [
                {
                    "id": 2,
                    "sourcePath": "U:",
                    "targetPath": "/opt/sybhttpd/localhost.drives/SATA_DISK"
                },
                {
                    "id": 3,
                    "sourcePath": "D:\\Mes films",
                    "targetPath": "/opt/sybhttpd/localhost.drives/NETWORK_SHARE/MYPC"
                },
                {
                    "id": 1,
                    "sourcePath": "T:",
                    "targetPath": "/opt/sybhttpd/localhost.drives/NETWORK_SHARE/SYNO"
                }
            ]
        },
        {
            "id": 1,
            "name": "C200",
            "deviceType": "PCH",
            "ipAddress": "192.168.1.30",
            "paths": [
                {
                    "id": 2,
                    "sourcePath": "U:",
                    "targetPath": "/opt/sybhttpd/localhost.drives/SATA_DISK"
                },
                {
                    "id": 3,
                    "sourcePath": "D:\\Mes films",
                    "targetPath": "/opt/sybhttpd/localhost.drives/NETWORK_SHARE/MYPC"
                },
                {
                    "id": 1,
                    "sourcePath": "T:",
                    "targetPath": "/opt/sybhttpd/localhost.drives/NETWORK_SHARE/SYNO"
                }
            ]
        },
        {
            "id": 1,
            "name": "C200",
            "deviceType": "PCH",
            "ipAddress": "192.168.1.30",
            "paths": [
                {
                    "id": 2,
                    "sourcePath": "U:",
                    "targetPath": "/opt/sybhttpd/localhost.drives/SATA_DISK"
                },
                {
                    "id": 3,
                    "sourcePath": "D:\\Mes films",
                    "targetPath": "/opt/sybhttpd/localhost.drives/NETWORK_SHARE/MYPC"
                },
                {
                    "id": 1,
                    "sourcePath": "T:",
                    "targetPath": "/opt/sybhttpd/localhost.drives/NETWORK_SHARE/SYNO"
                }
            ]
        },
        {
            "id": 2,
            "name": "PC-JLUC",
            "deviceType": "PC",
            "ipAddress": "192.168.1.19",
            "paths": [
                {
                    "id": 5,
                    "sourcePath": "/volume1/Media/",
                    "targetPath": "file:///T:"
                },
                {
                    "id": 6,
                    "sourcePath": "D:\\Mes films",
                    "targetPath": "file:///D:/Mes films"
                },
                {
                    "id": 4,
                    "sourcePath": "T:",
                    "targetPath": "file:///T:"
                },
                {
                    "id": 7,
                    "sourcePath": "U:",
                    "targetPath": "file:///U:"
                },
                {
                    "id": 8,
                    "sourcePath": "W:",
                    "targetPath": "file:///W:"
                }
            ]
        },
        {
            "id": 2,
            "name": "PC-JLUC",
            "deviceType": "PC",
            "ipAddress": "192.168.1.19",
            "paths": [
                {
                    "id": 5,
                    "sourcePath": "/volume1/Media/",
                    "targetPath": "file:///T:"
                },
                {
                    "id": 6,
                    "sourcePath": "D:\\Mes films",
                    "targetPath": "file:///D:/Mes films"
                },
                {
                    "id": 4,
                    "sourcePath": "T:",
                    "targetPath": "file:///T:"
                },
                {
                    "id": 7,
                    "sourcePath": "U:",
                    "targetPath": "file:///U:"
                },
                {
                    "id": 8,
                    "sourcePath": "W:",
                    "targetPath": "file:///W:"
                }
            ]
        },
        {
            "id": 2,
            "name": "PC-JLUC",
            "deviceType": "PC",
            "ipAddress": "192.168.1.19",
            "paths": [
                {
                    "id": 5,
                    "sourcePath": "/volume1/Media/",
                    "targetPath": "file:///T:"
                },
                {
                    "id": 6,
                    "sourcePath": "D:\\Mes films",
                    "targetPath": "file:///D:/Mes films"
                },
                {
                    "id": 4,
                    "sourcePath": "T:",
                    "targetPath": "file:///T:"
                },
                {
                    "id": 7,
                    "sourcePath": "U:",
                    "targetPath": "file:///U:"
                },
                {
                    "id": 8,
                    "sourcePath": "W:",
                    "targetPath": "file:///W:"
                }
            ]
        },
        {
            "id": 2,
            "name": "PC-JLUC",
            "deviceType": "PC",
            "ipAddress": "192.168.1.19",
            "paths": [
                {
                    "id": 5,
                    "sourcePath": "/volume1/Media/",
                    "targetPath": "file:///T:"
                },
                {
                    "id": 6,
                    "sourcePath": "D:\\Mes films",
                    "targetPath": "file:///D:/Mes films"
                },
                {
                    "id": 4,
                    "sourcePath": "T:",
                    "targetPath": "file:///T:"
                },
                {
                    "id": 7,
                    "sourcePath": "U:",
                    "targetPath": "file:///U:"
                },
                {
                    "id": 8,
                    "sourcePath": "W:",
                    "targetPath": "file:///W:"
                }
            ]
        },
        {
            "id": 2,
            "name": "PC-JLUC",
            "deviceType": "PC",
            "ipAddress": "192.168.1.19",
            "paths": [
                {
                    "id": 5,
                    "sourcePath": "/volume1/Media/",
                    "targetPath": "file:///T:"
                },
                {
                    "id": 6,
                    "sourcePath": "D:\\Mes films",
                    "targetPath": "file:///D:/Mes films"
                },
                {
                    "id": 4,
                    "sourcePath": "T:",
                    "targetPath": "file:///T:"
                },
                {
                    "id": 7,
                    "sourcePath": "U:",
                    "targetPath": "file:///U:"
                },
                {
                    "id": 8,
                    "sourcePath": "W:",
                    "targetPath": "file:///W:"
                }
            ]
        },
        {
            "id": 3,
            "name": "C200-2",
            "deviceType": "PCH",
            "ipAddress": "192.168.1.25",
            "paths": [
                {
                    "id": 9,
                    "sourcePath": "T:",
                    "targetPath": "/opt/sybhttpd/localhost.drives/NETWORK_SHARE/SYNO"
                },
                {
                    "id": 10,
                    "sourcePath": "D:\\Mes films",
                    "targetPath": "/opt/sybhttpd/localhost.drives/NETWORK_SHARE/MYPC"
                }
            ]
        },
        {
            "id": 3,
            "name": "C200-2",
            "deviceType": "PCH",
            "ipAddress": "192.168.1.25",
            "paths": [
                {
                    "id": 9,
                    "sourcePath": "T:",
                    "targetPath": "/opt/sybhttpd/localhost.drives/NETWORK_SHARE/SYNO"
                },
                {
                    "id": 10,
                    "sourcePath": "D:\\Mes films",
                    "targetPath": "/opt/sybhttpd/localhost.drives/NETWORK_SHARE/MYPC"
                }
            ]
        }
    ]
}

**Comment by modmax** [comment]
Before update run following SQL statements in database:

alter table player_path add column player_id BIGINT not null;

update player_path pp set pp.player_id=(select pip.player_info_id from playerinfo_playerpath pip where pip.player_path_id=pp.id) where pp.player_id=0;

DROP TABLE playerinfo_playerpath;

**Comment by jluc2808** [comment]
updated like specified 
tested OK after update and new version
