### ISSUE TITLE
image not found with player information 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#255]
Get http://jean_luc_seven:8888/yamj3/images/yamj-configbg.jpg 404 (Not Found)

doesn't find images under 
C:\Users\jean-luc\AppData\Local\Temp\jetty-0.0.0.0-8888-yamj3-core-3.0-SNAPSHOT.war-_yamj3-any-\webapp\WEB-INF\images

**Comment by modmax** [comment]
The image "yamj-configbg.jpg" was dropped a long time ago by stuart;
this was a background image.

Mostly it makes no sense to declare images as background images, if you haven't different images for different resolutions .. sometime the backrgound will be doubled, sometime it doesn't fir to the content and so on ... due browser resize; display with (1280*720 .. 1920*1080 .. 1929*1440) and so on.
Therefore Stuart has dropped the background image.

I removed the still existing references to that image in the player settings.

**Comment by jluc2808** [comment]
tested OK
