### ISSUE TITLE
api/boxset/13.json?dataitems=member,artwork&artwork=POSTER&sortby=title&sortdir=ASC

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#259]
return  boxset artwork and the skin needs member artwork
i explain 
this API is called with onclick on boxset itself and have to display members of the boxset selected 
so the result need to display member contents and member artwork 

now the results is the following 
"count": 1,
    "totalCount": 1,
    "queryDuration": "8ms",
    "queryTime": "2015-09-03 23:50:53 +0200",
    "status": {
        "status": 200,
        "message": "OK"
    },
    "options": {
        "sortby": "title",
        "sortdir": "ASC",
        "dataitems": [
            "member",
            "artwork"
        ],
        "id": 13,
        "artwork": "POSTER"
    },
    "baseArtworkUrl": "http://192.168.1.10:8888/artwork/",
    "baseMediainfoUrl": "http://192.168.1.10:8888/mediainfo/",
    "basePhotoUrl": "http://192.168.1.10:8888/photo/",
    "baseTrailerUrl": "http://192.168.1.10:8888/trailer/",
    "result": {
        "id": 13,
        "name": "Arthur et les Minimoys",
        "memberCount": 3,
        "watched": false,
        "members": [
            {
                "id": 257,
                "videoType": "MOVIE",
                "ordering": 3,
                "title": "Arthur 3 La Guerre Des Deux Mondes",
                "originalTitle": "Arthur 3 La Guerre Des Deux Mondes",
                "year": 2010,
                "releaseDate": "2010-10-13",
                "watched": false
            },
            {
                "id": 258,
                "videoType": "MOVIE",
                "ordering": 2,
                "title": "Arthur et la vengeance de Maltazard",
                "originalTitle": "Arthur et la vengeance de Maltazard",
                "year": 2009,
                "releaseDate": "2009-12-02",
                "watched": false
            },
            {
                "id": 256,
                "videoType": "MOVIE",
                "ordering": 1,
                "title": "Arthur et les Minimoys",
                "originalTitle": "Arthur et les Minimoys",
                "year": 2006,
                "releaseDate": "2006-12-13",
                "watched": false
            }
        ],
        "artwork": {
            "POSTER": [
                {
                    "id": 13,
                    "source": "BOXSET",
                    "artworkId": 549,
                    "locatedId": 13448,
                    "generatedId": 13430,
                    "artworkType": "POSTER",
                    "filename": "a/ar/Arthur et les Minimoys.boxset.poster.71huP95dyq51zgV4kEUKWyacEz2.default-poster.jpg"
                },
                {
                    "id": 13,
                    "source": "BOXSET",
                    "artworkId": 549,
                    "locatedId": 13447,
                    "generatedId": 13429,
                    "artworkType": "POSTER",
                    "filename": "a/ar/Arthur et les Minimoys.boxset.poster.he8Hk4J7So04KA9giNc5HZxPqW4.default-poster.jpg"
                }
            ]
        }
    }
}

to solve : artwork should have to be stored under members and should point to the members artwork

**Comment by modmax** [comment]
You can get the boxset member also with following query:

/api/index/video?include=boxset-1&dataitems=artwork&artwork=poster

The "boxset-1" is a filter for "include all videos for boxset with id 1".

**Comment by jluc2808** [comment]
i 'm already using the way you suggested , but i want to test the new api/boxset i find this fix to set
