### ISSUE TITLE
error while disabling person_id 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#260]
i run : 
api/person/disableonlinescan.json?id=17042&sourcedb=imdb

jetty response: 
[12.09.2015 14:19:07] INFO  org.yamj.core.api.json.PersonController  - Disable imdb online scan for person with ID '17042'

then 
api/person/17042.json?dataitems=status,filmography_status,artwork,biography,externalid

json response:
  "id": 17042
    },
    "baseArtworkUrl": "http://192.168.1.8:8888/artwork/",
    "baseMediainfoUrl": "http://192.168.1.8:8888/mediainfo/",
    "basePhotoUrl": "http://192.168.1.8:8888/photo/",
    "baseTrailerUrl": "http://192.168.1.8:8888/trailer/",
    "result": {
        "id": 17042,
        "name": "Dave Hill (II)",
        "firstName": "Dave",
        "lastName": "Hill (II)",
        "status": "DONE",
        "filmography_status": "DONE",
        "externalIds": [
            {
                "id": 17042,
                "externalId": "650413",
                "sourcedb": "allocine",
                "skipped": false
            },
            {
                "id": 17042,
                "externalId": "nm1661894",
                "sourcedb": "imdb",
                "skipped": false
            },
            {
                "id": 17042,
                "externalId": "1251377",
                "sourcedb": "tmdb",
                "skipped": false
            }
        ]

so imdb external_id isn't disabled as asked 
i take a look in db person_ids and imdb is still there for person_id 17042

**Comment by modmax** [comment]
Hi Jean-Luc,
I can't see any problem with the feature.

If i call "api/person/disableonlinescan.json?id=1&sourcedb=imdb"
I get the log message:
Disable imdb online scan for person with ID '1'

So the log message is different from you message, perhaps you have an older version???

Further on:
The external id will not be removed; therefore you have other calsl to update and delete any external IDs. Instead in the person table the field "skip_scan_api" will be enhanced with the skipped online scan sources. In your case "imdb" should be within that field.

If then the person details are called, then the external id for imdb is correctly set to "skipped:true" in my case.

**Comment by modmax** [comment]
Error was:
The IMDB api didn't return any biography ... even if the mini bio on web page is present.
I fixed this issue and use the bio from html page, when no bio is present for imdb api.

**Comment by jluc2808** [comment]
tested new imdb API and biography is now returned  -
