### ISSUE TITLE
set not generated 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#266]
i have added 3 movies (and ran the filescanner task) 
Le Seigneur des anneaux  la communauté de l'anneau [SET Le seigneur des anneaux-1] (2001) - 720p.bluray.x264.mkv
Le Seigneur des anneaux  le retour du roi [SET Le seigneur des anneaux-3] (2003) - 720p.bluray.x264.mkv
Le Seigneur des anneaux  les deux tours [SET Le seigneur des anneaux-2] (2002) - 720p.bluray.x264.mkv 

every single movie is ok (the filescanner and jetty)  store/get the movie but the boxset haven't been generated (no entry in the boxset table)

**Comment by modmax** [comment]
How are the video files named in the database (table: videodata)?

If there a SET is included, then the set is not correctly detected by the file scanner.
So you need to name the files correcty
See: https://github.com/YAMJ/yamj-v2/wiki/Boxed-Sets

If that also does not work I will take a look into it and do some tests.

**Comment by jluc2808** [comment]
the identifer (videotada) is : Le Seigneur Des Anneaux La Communaute De Lanneau_2001
in the videodata table there is no filename , here are the field i have in videodata (what is the one you want to see)


 identifier:  Le Seigneur Des Anneaux La Communaute De Lanneau_2001, 
 title Le Seigneur des anneaux : la communauté de l'anneau, 
 original_title: The Lord of the Rings: The Fellowship of the Ring, 
title_sort: Seigneur des anneaux : la communaute de l'anneau, 


there is no SET created 

the name is 
Le Seigneur des anneaux le retour du roi [SET Le seigneur des anneaux-3] - 720p.bluray.x264.mkv
i'm using the same name with yamjv2 and the SET is created correctly (that would say that named convention is OK)

**Comment by modmax** [comment]
Still open, cause some files are not detected correctly.

**Comment by jluc2808** [comment]
tested now ok
