### ISSUE TITLE
add feature to crop poster

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#268]
a lot of poster have black margin after transformation from 1200x1600 to 224x332 (or any other dimension which havn't the ratio 0,67)  

could we crop the generated poster to avoid this black margin (at the top) if asked by user 
- by parameter (crop_to_default_dimension) which could be used at any time for new poster
- by api to re-generate a single one

**Comment by modmax** [comment]
The artwork_profile contains the necessary informations.

Set the flag "normalize" to true, and the black margins should disappear, cause then the image will be streched and cropped if necessary.

Also there are some other parameters like "stretch"," rounded_courners" etc. which can be managed. But right now there is not management gui for the profiles; so this has to be done manually in the database table.

**Comment by jluc2808** [comment]
with the artwork_profile table the flag 'normalize' is already setted and the head black margins still stays when the original are 1600x1200 or any other value which aren't with 0,67 ratio

**Comment by modmax** [comment]
An already processed image will not be recreated again, even if the profile changes.

If normalized is set then you can just update all artwork located images by setting the status of the "false" cropped images to "UPDATED", so that new profile images will be created.

**Comment by jluc2808** [comment]
what i would said was , as 'normalyze' flag was already setted , all previous image should have been cropped when there were generated , the result wasn't what expected , every 1600x1200 are with black margin

i could regenarate some poster as suggested, but if havn't made any modification to the code i don't think that will give another result

**Comment by modmax** [comment]
This can be closed cause images can be regenerated via API or web page request.

**Comment by jluc2808** [comment]
tested ok
