### ISSUE TITLE
add videoSource or files to dataitems api api/index/video.json?

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#269]
to display overlay according to the videoSource , could you add either videoSource or files to the return dataitems with api/ndex/video

**Comment by modmax** [comment]
A VideoData object may have multiple media files. That may be parts of a video or just different versions of a video.
When each version contains a different videoSource, then the question is: Which videoSource should be returned for a movie or episode or season or series?
The video source itself is contained in the media files ... so from there they should be grabbed ...

**Comment by jluc2808** [comment]
i expect the one returned inside the files container of api/video/movie/620.json?dataitems=files

**Comment by modmax** [comment]
Which source should be display if you a video with 2 parts and therefore 2 files and each one has a different video source? Or the case, that you have multiple versions of a video: The cinema version from BluRay, a director's cut from TV in HD and a DVD version?
Therefore it's dificult to find a rule to match it all ...

**Comment by jluc2808** [comment]
i suggest : 
- if more than one videoSource , return "multi", with the list of all videoSource found
- if no source return "unknown", 
- if there is only one return single and the one found

**Comment by modmax** [comment]
When requesting a singleton video (movie/series/season/episode), then you can add following dataitem: videosource.

The call will then be something like this: http://localhost:8888/yamj3/api/video/movie/7.json?dataitems=videosource

The videosource will then be returned; if multiple video sources are contained, then "MULTIPLE" is returned inside video source.

**Comment by jluc2808** [comment]
my original asking is to add videosource inside api/index/video  (videosource was already returned inside files with api/video/movie) but is still not return with index/video

**Comment by jluc2808** [comment]
tested ok
