### ISSUE TITLE
return artwork sorted by date with create_timestamp 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#271]
api/person/6652.json?dataitems=artwork

when api call for a person with artwork , if the person have more than one artwork (photo) , could the results list of artwork (photo) be sorted by create_timestamp with descending or ascending order

**Comment by modmax** [comment]
Should this also be true for other artwork request, like posters for movies and so on?

**Comment by jluc2808** [comment]
yes , but isn't so needed , so 1rst priority is for photo
