### ISSUE TITLE
add release_date to API/index

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#277]
could you add in API/index /video

&sortby=release_date (DESC, ASC) 
and 
&dataitems=release_date

**Comment by modmax** [comment]
I've added the release date as return value.
The dataitems will not work, cause the release date is only present for movies and episodes; season and series don't have a release date (just start year and end year, or in case of seasons the season year). This means that the release date is not found for season and series (it's a null value in such cases, which will not be transfered in the JSON objects).

Aslo you can sort by release date, but it then must be called "releaseDate", cause that's the alias for the database column release_date in the queries and json response.

**Comment by jluc2808** [comment]
tested ok , 

after implementing this new sorting, looking at the results , the release_date isn't the right sorting parameter for the NEW function 
NEW function is :  show me all the new movie/tv show added to my jukebox since xx days 

generaly prefered output should be sorted by date - the last stored in the jukebox first , the oldest last (or by name , but this case doesn't have problem) 

so the date to take for sorting is the created_timestump rather than release_date 
i have opened a new issue to add this parameter
