### ISSUE TITLE
stagingsanity task doesn't started

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#278]
i have setted the staginsanity task to 2 minutes later and queued ==> no task started 
i have restarted yamj3 with a date for the staginsanity task earlier than the current date ==> no task started

as i see the stagingsanity disable by default , may i set a parameter somewhere to start the task , other than the update i have made

**Comment by modmax** [comment]
Set this to true in your static user properties:

```
# check staging sanity
yamj3.check.stagingSanity=false
```

If set it to false by default cause it may cause deletions, when the task is run and some subdirectories are on USB disks, which are not attached all the time.
