### ISSUE TITLE
problem with another world movie , can't select the right site to download

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#284]
i have added the movie :  with name Another World (2014).mkv 
and an NFO file which contains 
`<movie>
      <id moviedb="tmdb">120172</id>   
      <title>Another World</title>
      <titleSort>Another World</titleSort>
      <originalTitle>Another World</originalTitle>
</movie>`

and my setting in user.properties is 
yamj3.sourcedb.scanner.movie=allocine,tmdb,imdb

i always get a wrong movie from allocine : http://www.allocine.fr/film/fichefilm_gen_cfilm=979.html  which not the right one 
i enforce to delete (with API) this reference and get the imdb reference 1rst : http://www.imdb.com/title/tt1920846
i tried to skip imdb with API and update the movie , the poster isn't downloaded from tmdb always , if i want to delete the imdb reference (with API) everytime the reference is recreated 

2 remarks: the nfo isn't taken 1rst   ==> may i have to change 
yamj3.sourcedb.scanner.movie=allocine,tmdb,imdb  to yamj3.sourcedb.scanner.movie=nfo,allocine,tmdb,imdb

how could i delete the imdb reference without recreating the reference 1rst while scanning the movie

**Comment by modmax** [comment]
Hi Jean-Luc,
if you have a NFO, why don't you just add the allocine ID in it?
<id moviedb="allocine">xyz</id>
And also the imdb id?

As alternative you can update or remove the external ID for allocine and 
imdb via API call.


> i have added the movie : with name Another World (2014).mkv
> and an NFO file which contains
> |<movie>
> <id moviedb="tmdb">120172</id>
> <title>Another World</title>
> <titleSort>Another World</titleSort>
> <originalTitle>Another World</originalTitle>
> </movie>|
>
> and my setting in user.properties is
> yamj3.sourcedb.scanner.movie=allocine,tmdb,imdb
>
> i always get a wrong movie from allocine : 
> http://www.allocine.fr/film/fichefilm_gen_cfilm=979.html which not the 
> right one
> i enforce to delete (with API) this reference and get the imdb 
> reference 1rst : http://www.imdb.com/title/tt1920846
> i tried to skip imdb with API and update the movie , the poster isn't 
> downloaded from tmdb always , if i want to delete the imdb reference 
> (with API) everytime the reference is recreated
>
> 2 remarks: the nfo isn't taken 1rst ==> may i have to change
> yamj3.sourcedb.scanner.movie=allocine,tmdb,imdb to 
> yamj3.sourcedb.scanner.movie=nfo,allocine,tmdb,imdb
>
> how could i delete the imdb reference without recreating the reference 
> 1rst while scanning the movie
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/YAMJ/yamj-v3/issues/284>
>


-- 

Markus Bader
Himbeerweg 5
24161 Altenholz

Tel.:   0431 / 66 704 77
Fax:    0431 / 66 604 76
Mobil:  0171 / 37 26 764
E-Mail: markus@markusbader.de

**Comment by jluc2808** [comment]
because there is no entry in allocine for this movie and when i want to remove external IMDB Id always the imdb external Id is rearmed

**Comment by modmax** [comment]
Then set
`<id moviedb="tmdb">120172</id>
<id moviedb="allocine">-1</id>
`
This means, that no allocine scan will be done, and the next scanner will be used.
