### ISSUE TITLE
api with newest include doesn't returned series (only movies)

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#290]
if i try 
api/index/video.json?type=movie,series&dataitems=status,boxset,rating,videosource&artwork=poster&watched=all&include=newest-80-file&sortby=videoYear DESC

results return only movies 

api/index/video.json?type=series&dataitems=status,boxset,rating,videosource&artwork=poster&watched=all&include=newest-80-file&sortby=videoYear DESC

return 0 results 

should return 1 result (tv series) which have been stored today

**Comment by modmax** [comment]
I have no problems with that.

I added a new episode, and then the query returned one new series.

I think that your problem ist, that your newest episode is more than 80 days old according to the file date
and therefor no series is displayed.

If you increase the value to "newest-5000-file", then you should see something ...
