### ISSUE TITLE
with tvdb season id isn't scrapped and stored in season_ids 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#295]
now the series_ids is ok with the tvdb scrapping and storing  , is there a solution to fetch and store the real seasonId rather than the seriesId value is season_ids table ? 

ex: game of thrones season 6 
series_ids : '121361'  sourcedb: tvdb 
season_ids: '121361'  sourcedb: tvdb    ==> the right season_ids  is : 651357

**Comment by modmax** [comment]
Please use the tvdb plugin with version 3.0.2, which should be available in some minutes on the mediaplayersite.

In order ro update the season ids use following sql statements:
`update season sea set sea.status='UPDATED' where sea.status='DONE' and exists (select 1 from season_ids ids where ids.sourcedb='tvdb' and ids.season_id=sea.id);`
`delete from season_ids where sourcedb='tvdb';`

**Comment by jluc2808** [comment]
tested ok
