### ISSUE TITLE
how could we populate mediainfo after the video has been already stored

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#307]
for some reason (a lot of could happen) some video are scrapped and stored without mediainfo populated (running time, audio description, video settings, .....) how could i repopulate all these info after the video has been already stored 

i tried to set an updated value to the media or the file but these refetch plot , artwork, and outside info from sites but doesn't run the mediainfo local program

**Comment by modmax** [comment]
Quick fix: set UPDATED flag in mediafile table ...

There will be needed another mechanism to set the mediafile object (not videodate) object to UPDATED
in order to rerun mediainfo.

**Comment by jluc2808** [comment]
yes the quick fix is OK , could that update be applied via API ?

**Comment by jluc2808** [comment]
i have found :  need to add in the skin UI a button to update mediafile with 
/yamj3/api/file/update/{stage_id}

will be done in the next bikini version

**Comment by jluc2808** [comment]
the api call is OK , the only problem is because the update is only made while filescanner is running 
this bring to the feature of start the filescanner from the skin , long discussion, which isn't closed

**Comment by modmax** [comment]
If will take a look into it, if I have the time . Perhaps there is a possibility to processe updated stage files, even if there is no filescanner run; just the way how videodate is processed when set to updated.

**Comment by modmax** [comment]
The call /yamj3/api/file/update/{stage_id} can be used for this.
If the stage file is for a media file, then the media file will be set tp UPDATED
(instead of the state file) and the media file scan will be triggered.
