### ISSUE TITLE
warn at each start

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#308]
log4j:WARN No such property [maxBackupIndex] in org.apache.log4j.DailyRollingFileAppender.
log4j:WARN No such property [maxFileSize] in org.apache.log4j.DailyRollingFileAppender.
log4j:WARN No such property [maxFileSize] in org.apache.log4j.DailyRollingFileAppender.
log4j:WARN No such property [maxBackupIndex] in org.apache.log4j.DailyRollingFileAppender.

**Comment by modmax** [comment]
The DailyRollingFileAppender does not support those values (makes really no sense for daily rolling).
Remove those values from the log4-filescanner.properties, which has to be done within
you own log4j-filescanner.properties.

log4j.appender.LOGFILE.MaxFileSize
log4j.appender.LOGFILE.MaxBackupIndex
log4j.appender.ERRORFILE.MaxFileSize
log4j.appender.ERRORFILE.MaxBackupIndex

**Comment by jluc2808** [comment]
warning are still there 

log4j.appender.LOGFILE.MaxFileSize
log4j.appender.LOGFILE.MaxBackupIndex
log4j.appender.ERRORFILE.MaxFileSize
log4j.appender.ERRORFILE.MaxBackupIndex

properties are also in log4j.core.properties 


comment : 
if i set these value in the user log4j-filescanner.user.properties or log4j-core.user.properties, i will still get  the problem (warning). 
I have already some log with more than 5MB (the biggest i found is 365MB when i rescan a lot of movie with a big amount of error ) which could hang the system because of too much place, so switch at 5MB and remove after 7 logs could be useful. This need to allow to rollback 
log4j.appender.ERRORFILE=org.apache.log4j.DailyRollingFileAppender
log4j.appender.LOGFILE=org.apache.log4j.DailyRollingFileAppender
in log4j-filescanner.user.properties and log4j-core.user.properties
