### ISSUE TITLE
imdb problems

### ISSUE THREAD

**Issue by slothrop49** [YAMJ/yamj-v3#312]
When the imdb plugin is used for Movies (yamj3.sourcedb.scanner.movie=imdb) and either 

1. the genre on imdb includes **Documentary** or **Short**, or
2. the movie is either a TV Mini-Series, TV Special or Video on Imdb.

then no artwork is added (either from imdb or from the folder with the movie), no details are pulled from imdb, details are only extracted from any NFO file and from mediainfo  

the issue and checks can be found at http://www.networkedmediatank.com/showthread.php?tid=74245&pid=680472#pid680472

**Comment by modmax** [comment]
If this problem still exists after followed the comments given on networkmediatank, then pleas reopen this issue.

**Comment by slothrop49** [comment]
As per my notes in http://www.networkedmediatank.com/showthread.php?tid=74245&pid=680513#pid680513 the imdb scanner on its own will stop if it encounters

1. the genre on imdb includes Documentary or Short, or
2. the movie is either a TV Mini-Series, TV Special or Video on Imdb.

it will not pull artwork (even from the movie folder), download movie data from imdb or any person information.

While using **yamj3.sourcedb.scanner.movie=imdb,tmdb** provides a useful workaround, by forcing the scan to move on and scrape from thetvdb.com, the imdb scanner itself is not working.

I am therefore re-opening this item.
