### ISSUE TITLE
Include the plugins in the release

### ISSUE THREAD

**Issue by dav1170** [YAMJ/yamj-v3#317]
Hello, 

After my first installation, I'll give you a list of different feedbacks I have to improve the setup process.
First of all, the plugins design is really powerfull and allow to easily customize how yamj process files.
Many of the posts I have readed before installing yamj does not explain the plugins process.
It could be interesting to provide an archive with both yamj, +eversion + the common plugins in a github repository.
It would help users which doesn't already know the yamj3 concepts to help them to deploy their instance.

**Comment by jluc2808** [comment]
already done with this thread (with HSQL db or Mysql db) 
http://www.networkedmediatank.com/showthread.php?tid=74382

**Comment by dav1170** [comment]
Oh ok, thank you!
It wasn't the forum topic I used to install yamj3 so my yamj3 release wasn't embedded the plugins.
nice to see that there is already a release which include plugins.

But don't forget that users (developers like me) will try to find the latest info regarding a software on the official website (such as omertron or github for yamj) and it seems this release is not already available on these websites.

regards

**Comment by jluc2808** [comment]
i need to update, but as it's a big work (very big) i'm waiting to finish some update with libraries feature to test all db (HSQL and MySQL) then update 
but as with every embedded package, the package is construct to help for beginner or initial install, for all other user you need to update new component directly from yamj3 version (from mediaplayersite http://mediaplayersite.com/YAMJv3), plugin , bikini , eversion_yamj3 , java , Mkvtoolkit, mediainfo , ......,  when available.  of course all these component needs to be compatible (as you now computer , you now that )
