### ISSUE TITLE
Exclude the core and filescanner folders from browsing by default

### ISSUE THREAD

**Issue by dav1170** [YAMJ/yamj-v3#319]
Hello,

I was a bit surprised when launching for the first time the file scanner that it also browse both core and filescanner folders (my main jukebox folder is located in my videos share).

It could be interesting to exclude by default browsing this folder to avoid browsing possible existing pictures in core and filescanner folders.

**Comment by jluc2808** [comment]
depending where are you libraries (movies and tvset) you are able to exclude folder with parameter within 
yamj3-filescanner.user.properties 
adding all dir or subdir 
# Lowercase list of directories to ignore
filescanner.ignore.dir=sample,tmp,temp,RECYCLE.BIN,._,@eaDir
or 
with 
filescanner.ignore.video=
# If the file ".no_image.yamj" is found in the directory, files with these extensions will be skipped
filescanner.ignore.image=
# If the file ".no_other.yamj" is found in the directory, files with these extensions will be skipped
filescanner.ignore.other=
# Should the NMJ files (.no_all.nmj, .no_video.nmj, .no_photo.nmj) be respected?

**Comment by dav1170** [comment]
Hello Jluc2808,

I know that we are able to do it. I've done it too.
But when we set up our own set up, we don't know all the options are and all the features involved in the yamj software.
So my request was perhaps to add a .no_all.nmj file in the core and filescanner packages to ensure that these folders won't be browsed if we mess up to set the appropriate configuration when running for the first time yamj.

**Comment by jluc2808** [comment]
by default .mjbignore is setted (directory with that file is ignored) so the question is: 
-  do we have to set nmjcompliant to true or false by default (now it's setted to false) 
you feeling is yes , i'm not totaly convinced , perhaps modmax or stuart have an opinion

**Comment by dav1170** [comment]
Hello,

When running for the first time my jetty's setup, I'm sure that this option was setted to false.
After updating this value to true and launch back file indexation, everything was fine. But I'm not sure that this first run does not involved some issues I previously reported.
So this is the reason I reported this issue: ensure that when we ran for the first time the file indexation, we'll don't have side effects too.

**Comment by jluc2808** [comment]
sorry but i read carfully and another time the issue reported and i don't understand what is the real  issue 
- when you launch your filescanner with -d storage_of_your_video 
if the core and filescanner folder are scanned that would say :  your 'storage_of_your_video' contains the yamj3 installation 
it's not recommended to store together (inside the same hierarchy) yamj3 mecanism and video folder
1 - specify the subdirectory where the video are stored not the root folder 
2 - just add the file .mjbignore  inside core and filescanner folder 
3 - even it's not added , i don't think (no reason) that the scan of core or filescanner folder have any influences on the scrapping itself 
(because in those folder there is no file with the an available extension jpg, png, mkv, ....., avi,mp4, so filescanner and jetty skip those files)

**Comment by Omertron** [comment]
You should install your YAMJ instance such that the YAMJ code is not in the same folder structure as your videos. This way the folders will not be scanned by YAMJ.

````
C:\
+-- YAMJ
+-- TV Shows
+-- Movies
````
This way you can scan ````Movies```` and ````TV Shows```` separately.

**Comment by dav1170** [comment]
hello,

sorry for this late answer.
@Omertron : Yes I should. but my movies are located in a shared folder in my NAS and, If I use your suggested directory tree, I have to run multiple schedule tasks to update my library. This is why when running filescanner directory tree the library folder is /volume1/videos.

@jluc2808 : you are completely right, my yamj folder is inside my libary folder. My answer to omertron explain why. You are also completely right that I shouldn't. But as I suggested many times here or in my networkmediatank topics, installation and configuration is a nightmare. you say this is not recommended: probably, but how is it explain? in readme file? no. in the github rd file? no. in the tutorials available in both networkmediatank and the french popcorn hour forums? no.

And you are wrong for the jpg files: we can have some jpg files in the core folder with this process: after installing the core yamj3 and being able to run it, I've added the eversion skin from the web interface. It has been installed in the subolder "skins" in the core directory. Why? I don't know. but when I was running the filescanner with /volume1/videos, jpg files in the jukebox/core/skins were also indexed.

For sure, these "errors" come from an unexpected usage of yamj3. But, as I previously mentioned,  I cannot find in the different documentations something which explain clearly how to set up yamj3.

So this is the reason why I was suggesting to add this ignore file in the package? to let users like I was when running for the first time the filescanner to avoid scanning also the jukebox folder.

But for my own usage, I do not require anymore this feature.

regards

**Comment by Omertron** [comment]
I thought the ignore file was in there as default, although it's been a while since I looked into it, so I shall have to add it if it is not there (and ensure the filescanner respects it).

**Comment by jluc2808** [comment]
i will add the .mjbignore file inside the default yamj3 folder

**Comment by Omertron** [comment]
Add it to all the sub-projects if its not already there
