### ISSUE TITLE
http://localhost:8888/yamj3/ doesn't refresh 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#42]
http://localhost:8888/yamj3/ command doesn't refresh each time 

there is 2 problems :

- until jetty is running all the files (include .css) are locked by jetty (unable to update the .css file, because it's lock by another program, in this case jetty)
- when i stop jetty the program is released - so i could update the file (but that is not needed, because if i restart jetty , there is another instance of jetty-temp which created) , at this point , as there is no order to don't cache the index.html program the browser always play the one which is stored in cache.

so for me to solve both problems
1 - when the http://localhost:8888/yamj3/ command have finish the jetty call , there is some program to clean to released the ressources used by the command
2 - the command http://localhost:8888/yamj3/ should tell to the browser to uncache the command

**Comment by modmax** [comment]
Closed
