### ISSUE TITLE
apiary person / movie search by alphabetic letter 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#56]
as far as you are on the API features could you add some alphabetic search/list for Person / Movie 
As person are stored like firstName LastName, and movies are stored with 'the', 'a' ...... actual search to construct alphabetical list isn't allowed 
1 - for Person 
-  the API could build an alphabetical search based on the LastName 
- return the list of alphabetical entries available, 
- for each alphabetic entry the list of Person selected 
- with an optional  selector actor/writer/author
- with start/max and paging
- with asc/desc
- with some selector field year of birthday/ death  /  year of deathday /born country /.....

2 - for Movies/TV/Seasons/series/Episode
- the API could build an alphabetical search based on the Name without 'list of terms' 
- return the list of alphabetical entries available,
-  for each alphabetic entry the list of Movies/TV/Seasons/series/Episode 
- with an optional selector type of video  
- with start/max and paging
- with some selector field aired date/new /genre/.....

**Comment by modmax** [comment]
For alphabetical search you can also use:

* http://localhost:8888/yamj3/api/index/person?field=last_name&search=S&mode=start
Return all persons where last name starts with S (case insensitive)

* http://localhost:8888/yamj3/api/index/person?field=first_name&search=S&mode=start
Return all persons where first name starts with S (case insensitive)

For getting the alphabetical list (based on last_name):
* http://localhost:8888/yamj3/api/alphabetical/list?type=person

This issue has already been fixed.

**Comment by jluc2808** [comment]
tested works perfect
