### ISSUE TITLE
API to return all Tv shows

### ISSUE THREAD

**Issue by cptjhmiller** [YAMJ/yamj-v3#68]
As title, part of an YAMJ3 <-> trakt.tv sync feature for Pchtrakt.

Minimum information needed to be returned would be
Title
IMDB id
Thetvdb id
Watched status

If it would work better for the API call for setting the watched status a YAMJ3 DB item id could also be returned so instead of calling the API to mark [Show Title, Season, Episode] as watched we could do mark [YAMJ3 id]

**Comment by Omertron** [comment]
There are several new methods added to allow watched / unwatched.

/api/watched/movie/{yamj_id}

replace movie with season, series, episode

**Comment by modmax** [comment]
Use /api/list/series to return the needed movie informations
