### ISSUE TITLE
API to return all Movies

### ISSUE THREAD

**Issue by cptjhmiller** [YAMJ/yamj-v3#69]
As title, part of an YAMJ3 <-> trakt.tv sync feature for Pchtrakt.

Minimum information needed to be returned would be
Title
IMDB id
The movie db id
Watched status

If it would work better for the API call for setting the watched status a YAMJ3 DB item id could also be returned so instead of calling the API to mark [Title, year] as watched we could do mark [YAMJ3 id]

**Comment by modmax** [comment]
Use /api/list/movies to return the needed movie informations
