### ISSUE TITLE
Cache external data, such as weather

### ISSUE THREAD

**Issue by Omertron** [YAMJ/yamj-v3#7]
Caching calls to external data. e.g. weather, youtube trailers, etc. 
Things we can call via your api, you can cache the data for a set amount of time but we don't need right away. For example, I know almost everything has a youtube trailer from eversion/yamj current support. so we can make the call to get the trailer when someone tries to view it with minimal delay to find one and start to play it.

**Comment by modmax** [comment]
The main purpose of YAMJ v3 is to handle scanned movie; and not to cache external data the API clients may want. Therefore the API client itself has to take care.
