### ISSUE TITLE
API to return list of available alphabetical movie/series entries 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#83]
add an API to return only available alphabetical entries for movie / series / people 
allow to get the position of the current movie in the list

**Comment by Omertron** [comment]
Can you expand on this some more please?

**Comment by jluc2808** [comment]
already implemented with api/alphabetical/list.json?type={index_type} , but undocumented in apiary.io

still stay an issue with #204

**Comment by modmax** [comment]
Closes, cause #204 is closed now

**Comment by jluc2808** [comment]
tested ok
