### ISSUE TITLE
add REGEX method to the search mode 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#88]
could you add a REGEX method to the search mode that allow regex expression 

this will allow to skip ' le, la, les, the, a, an, ....' in movie search 
this will allow to skip 1rst name in person search

**Comment by modmax** [comment]
Each movie, series and season contains a field "title_sort" which can be used for search,
For persons you can search in last_name instead name for matches.

That should be enough ... also it's very difficult to transport regular expressions via http get/post methods according to the special characters used in regexp.
